name: go-fortune-workflow

# trigger
on:
  push:
    branches:
      - "release/v[0-9]+.[0-9]+"

jobs:
  # name of your job
  go-fortune-job:
    name: Go Fortune Workflow Job
    # runner
    runs-on: ubuntu-latest
    permissions: write-all
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    # steps in this job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: /home/runner/work/go-fortune/go-fortune/release/v0.3
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: release/v0.3
          ignore-unfixed: false
          format: "table"
          output: "trivy-report.txt"
          severity: "HIGH"
          vuln-type: os, library
          scanners: vuln,secret,config
      - name: Upload report to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACKTOKEN }}
          channel_id: ${{ secrets.SLACKCHANNELID }}
          file_path: "trivy-report.txt"
          file_type: "text"
          initial_comment: "Post by slack-upload-file, added scope"
          # thread_ts: 'option'
      # - name: Set up QEMU
      # uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      # uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      # uses: docker/login-action@v3
      # with:
      # username: ${{ secrets.DOCKERHUBUSERNAME }}
      # password: ${{ secrets.DOCKERHUBACCESSTOKEN }}
      # - name: Build and push
      # uses: docker/build-push-action@v5
      # with:
      # file: /home/runner/work/go-fortune/go-fortune/release/v0.3/Dockerfile
      # push: true
      # tags: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune:v0.3
      # - name: Send custom JSON data to Slack workflow
      # id: slack
      # uses: slackapi/slack-github-action@v1.26.0
      # with:
      # payload: |
      # {
      # "text": "Push commit triggered workflow",
      # "blocks": [
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Ref*\n${{github.ref}}"
      # },
      # {
      # "type": "mrkdwn",
      # "text": "*Event*\n${{github.sha}}"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Actions URL*\nBuild and Push"
      # },
      # {
      # "type": "mrkdwn",
      # "text": "*Commit*\n${{github.event.head_commit}}"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Image build and signed*"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Name:* Kevin Oh"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Matriculation:* A0023945E"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Email:* ohsl265@gmail.com"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Git:* ${{github.repository}}"
      # }
      # ]
      # },
      # {
      # "type": "section",
      # "fields": [
      # {
      # "type": "mrkdwn",
      # "text": "*Image:* https://hub.docker/repository/docker/ko812/go-fortune"
      # }
      # ]
      # }
      # ]
      # }
      # env:
      # SLACK_WEBHOOK_URL: ${{ secrets.MYTUNNEL }}
      # SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
