name: go-fortune-workflow

# trigger
on:
  push:
    branches:
      - "release/v[0-9]+.[0-9]+"

jobs:
  # name of your job
  scan-vulnerabilities:
    name: Scan Vulnerabilities
    # runner
    runs-on: macos-latest
    permissions: write-all
    if: "!contains( github.event.head_commit.message, '#NORUN')"
    # steps in this job
    outputs:
      VunerabilityFound: ${{ steps.run-trivy.outputs.vunerability_found }}
      NoVulnerabilityFound: ${{steps.run-trivy.outputs.no_vunerability_found }}
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Install Trivy
        run: |
          brew install trivy
      - name: Manual run trivy scan job
        id: run-trivy
        run: |
          cd ${{github.ref_name}}
          trivy fs --format table --scanners vuln,secret,misconfig --severity HIGH --output trivy.txt .
          if [ -s trivy.txt ]; then
            echo "vunerability_found=true" >> $GITHUB_OUTPUT
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            git add trivy.txt
            git commit -m "Add changes" -a
            git push -u origin ${{github.ref_name}} 
            SHA=$(git rev-parse HEAD)
            echo "::set-output name=commitid::$SHA"
          else
            echo "no_vunerability_found=true" >> $GITHUB_OUTPUT
          fi
  Start-Reporting-Vulnerabilities:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    if: needs.scan-vulnerabilities.outputs.VunerabilityFound
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Send Report to Slack Dipsa58 channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path-parsed: false
          payload: |
            {
              "text": "Vulnerabilities found in latest push",
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Ref*\n${{github.ref}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Event*\n${{github.event_name}}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Actions URL*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{github.job}}>",
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*\n${{github.sha}}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Scan failed - ${{ secrets.DOCKERUSERNAME }}*\nFailed trivy scan, see uploaded report"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Powered by rtCamp's GitHub Actions Library"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MYTUNNEL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Upload report to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACKTOKEN }}
          channel_id: ${{ secrets.SLACKCHANNELID }}
          file_path: "${{github.workspace}}/${{github.ref_name}}/trivy.txt"
          file_type: "text"
          initial_comment: "Post by slack-upload-file, trivy scan vulnerabilities report"
  Build-Push-Sign-And-Notify:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    if: needs.scan-vulnerabilities.outputs.NoVulnerabilityFound
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          file: ${{github.workspace}}/${{github.ref_name}}/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune:${{github.sha}}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Sign image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ${TAG}
        env:
          TAG: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune@${{ steps.build-and-push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path-parsed: false
          payload: |
            {
                "text": "Push commit triggered workflow",
                "blocks": [
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Ref*\n${{github.ref}}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Event*\n${{github.sha}}"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Actions URL*\nBuild and Push"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Commit*\n${{github.event.head_commit.message}}"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Image build and signed*"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Name:* Kevin Oh"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Matriculation:* A0023945E"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Email:* ohsl265@gmail.com"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Git:* ${{github.repository}}"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Image:* https://hub.docker/repository/docker/ko812/go-fortune"
                            }
                        ]
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MYTUNNEL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
