name: go-fortune-workflow

# trigger
on:
  push:
    branches:
      - "release/v[0-9]+.[0-9]+"

jobs:
  # name of your job
  scan-vulnerabilities:
    name: Scan Vulnerabilities
    # runner
    runs-on: macos-latest
    permissions: write-all
    if: "!contains( github.event.head_commit.message, '#NORUN')"
    # steps in this job
    outputs:
      VunerabilityFound: ${{ steps.run-trivy.outputs.vunerability_found }}
      NoVulnerabilityFound: ${{steps.run-trivy.outputs.no_vunerability_found }}
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Install Trivy
        run: |
          brew install trivy
      - name: Manual run trivy scan job
        id: run-trivy
        run: |
          cd ${{github.ref_name}}
          trivy fs --format table --scanners vuln,secret,misconfig --severity ${{ vars.SCAN_SEV_LEVEL }} --output trivy.txt .
          if [ -s trivy.txt ]; then
            echo "vunerability_found=true" >> $GITHUB_OUTPUT
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            git add trivy.txt
            git commit -m "Add changes" -a
            git push -u origin ${{github.ref_name}} 
            SHA=$(git rev-parse HEAD)
            echo "::set-output name=commitid::$SHA"
          else
            echo "no_vunerability_found=true" >> $GITHUB_OUTPUT
          fi
  Start-Reporting-Vulnerabilities:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    if: needs.scan-vulnerabilities.outputs.VunerabilityFound
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Notify to Slack using rtCamp
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: mytunnel
          SLACK_USERNAME: SL Kevin Oh
          SLACK_TITLE: "*Scan failed - ${{ secrets.DOCKERUSERNAME }}*"
          SLACK_MESSAGE: "Failed trivy scan, see uploaded report"
          SLACK_WEBHOOK: ${{ secrets.MYTUNNEL }}
          SLACK_FOOTER: <https://github.com/rtCamp/action-slack-notify|Powered By rtCamp's GitHub Actions Library>
      - name: Upload report to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACKTOKEN }}
          channel_id: ${{ secrets.SLACKCHANNELID }}
          file_path: "${{github.workspace}}/${{github.ref_name}}/trivy.txt"
          file_type: "text"
          initial_comment: "Post by slack-upload-file, trivy scan vulnerabilities report"
      - name: Terminate in Failure
        run: |
          fail
  Build-Push-Sign-And-Notify:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    if: needs.scan-vulnerabilities.outputs.NoVulnerabilityFound
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          file: ${{github.workspace}}/${{github.ref_name}}/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune:${{github.sha}}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Sign image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ${TAG}
        env:
          TAG: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune@${{ steps.build-and-push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
      - name: Get Commit SHA substring
        id: get-sha-substring
        run: |
          echo "cutid=$(echo ${{github.sha}} | head -c 6)" >> $GITHUB_OUTPUT
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path-parsed: false
          payload: |
            {
                "text": "Push commit triggered workflow",
                "blocks": [
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Ref*\n${{github.ref}}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Event*\n${{github.event_name}}"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Actions URL*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{github.job}}>"
                            },
                            {
                                "type": "mrkdwn",
                                "text": "*Commit*\n<${{github.repositoryUrl}}|${{ steps.get-sha-substring.outputs.cutid}}>"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": "*Image build and signed*"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "text": "*Name:* <@${{ secrets.SLACK_USERNAME }}>"
                    },
                    {
                        "type": "section",
                        "text": "*Matriculation:* A0023945E"
                    },
                    {
                        "type": "section",
                        "text": "*Email:* ohsl265@gmail.com"
                    },
                    {
                        "type": "section",
                        "text": "*Git:* <${{ github.server_url }}/${{ github.repository}}>"
                    },
                    {
                        "type": "section",
                        "text": "*Image:* <https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUBUSERNAME }}/go-fortune/general>"
                    },
                    {
                        "type": "section",
                        "text": "Powered By rtCamp's GitHub Actions Library"
                    }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MYTUNNEL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
