name: go-fortune-workflow

# trigger
on:
  push:
    branches:
      - "release/v[0-9]+.[0-9]+"

jobs:
  # name of your job
  scan-vulnerabilities:
    name: Scan Vulnerabilities
    # runner
    runs-on: ubuntu-latest
    permissions: write-all
    if: "!contains( github.event.head_commit.message, '#NORUN')"
    # steps in this job
    outputs:
      VulnerabilityFound: ${{ steps.set-scan-result.outputs.vulnerability_found }}
      NoVulnerabilityFound: ${{steps.set-scan-result.outputs.no_vulnerability_found }}
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Run trivy scan
        id: run-trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "table"
          output: "trivy.txt"
          exit_code: 1
          severity: "HIGH"
      - name: Set Output When Vulnerabilities Found
        id: set-scan-result
        run: |
          mv trivy.txt ${{github.ref_name}}/trivy.txt
          cd ${{ github.ref_name }}
          if [ -s trivy.txt ]; then
            echo "vulnerability_found=true" >> $GITHUB_OUTPUT
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            git add trivy.txt
            git commit -m "Add changes" -a
            git push -u origin ${{github.ref_name}}
          else
            echo "no_vulnerability_found=true" >> $GITHUB_OUTPUT
          fi
  Start-Reporting-Vulnerabilities:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    if: needs.scan-vulnerabilities.outputs.VulnerabilityFound
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Notify to Slack using rtCamp
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: mytunnel
          SLACK_USERNAME: SL Kevin Oh
          SLACK_TITLE: "*Scan failed - ${{ secrets.DOCKERUSERNAME }}*"
          SLACK_MESSAGE: "Failed trivy scan, see uploaded report"
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_SUBMISSION_WEBHOOK }}
          SLACK_FOOTER: <https://github.com/rtCamp/action-slack-notify|Powered By rtCamp's GitHub Actions Library>
      - name: Upload report to Slack
        uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.DIPSA58_CICD_BOT_TOKEN }}
          channel_id: ${{ secrets.SLACK_TEST_SUBMISSION_CHANNEL_ID }}
          file_path: "${{github.workspace}}/${{github.ref_name}}/trivy.txt"
          file_type: "text"
          initial_comment: "Post by slack-upload-file, trivy scan vulnerabilities report"
      - name: Terminate in Failure
        run: |
          fail
  Build-Push-Sign-And-Notify:
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    if: needs.scan-vulnerabilities.outputs.NoVulnerabilityFound
    steps:
      - name: Checkout
        id: Checkout-step
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}
          path: ${{github.workspace}}/${{github.ref_name}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          file: ${{github.workspace}}/${{github.ref_name}}/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune:${{github.sha}}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Sign image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ${TAG}
        env:
          TAG: ${{secrets.DOCKERHUBUSERNAME}}/go-fortune@${{ steps.build-and-push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
      - name: Notify to Slack using rtCamp
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: mytunnel
          SLACK_USERNAME: SL Kevin Oh
          SLACK_TITLE: "*Image Built and Signed*"
          SLACK_MESSAGE: "*Name*: <@${{ secrets.SLACK_USERNAME  }}>\n*Matriculation*: A0023945E\n*Email*: E1332822@u.nus.edu\n*Git*: <${{github.repositoryUrl}}>\n*Image*: <https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUBUSERNAME }}/go-fortune/general>"
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_SUBMISSION_WEBHOOK }}
          SLACK_FOOTER: <https://github.com/rtCamp/action-slack-notify|Powered By rtCamp's GitHub Actions Library>
